version: "3.7"
services:

  postgres:
    image: postgres:11
    container_name: travel-db-postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - postgres.env
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - travel-guide

  adminer:
    image: adminer
    container_name: travel-db-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - travel-guide

networks:
 travel-guide:
   driver: bridge

volumes:
  static:
  dbdata:
