export const DatabaseConst = {
    CATEGORIES_TABLE: 'categories',
    FILES_TABLE: 'files',
    PLACES_TABLE: 'places',
    PLACE_CATEGORY_TABLE: 'place_category',
    PLACE_FILE_TABLE: 'place_file',
    ROUTES_TABLE: 'routes',
    ROUTE_CATEGORY_TABLE: 'route_category',
    PLACE_ROUTE_TABLE: 'place_route',
    MAIN_SECTIONS_TABLE: 'main_sections',
    SUBSECTIONS_TABLE: 'subsections',
    ARTICLES_TABLE: 'articles',
    ARTICLE_FILE_TABLE: 'article_file',
    AREAS_TABLE: 'areas',
    USERS_TABLE: 'users',
    AR_TABLE: 'ar',
    AR_FILE_TABLE: 'ar_files',
    ADDITIONAL_MATERIAL_TABLE: 'additional_material',
    AR_AM_TABLE: 'ar_additional',
    PLACE_AM_TABLE: 'place_additional',
    LINK_TABLE: 'link',
    NEWS_TABLE: 'news',
    NEW_FILE_TABLE: 'news_file',
};
